# CONFIG FILE FOR AN EXPERIMENT

data_dir: '/data/GP_FBANK_ALL_39/'
speech_metadata: '/RSA_word_phonology/metadata/gp_words_metadata_train_valid_32k_x.tsv'
model_save_dir: '/RSA_word_phonology/inprogress_models/'
seed: 1248 #1358
stimuli_language: 'DEU' # CZE DEU
model_languages: 'POR CZE POL RUS BUL FRA DEU' #  POR CZE POL RUS BUL FRA DEU
eval_split: 'DEV' #DEV' #EVA

pretrained_models:
    POR: '17072021_16_59_59_AWEs_2BiGRU_1024d_pretrained_CAE_TF03_POR_FBANK_145.pth'
    #CZE: '13072021_10_35_41_AWEs_2BiGRU_1024d_siamese_FBANK_87.pth'
    CZE: '15072021_00_34_46_AWEs_2BiGRU_1024d_pretrained_CAE_TF03_CZE_FBANK_97.pth'
    POL: '16072021_14_41_15_AWEs_2BiGRU_1024d_pretrained_CAE_TF03_POL_FBANK_140.pth'
    #RUS: '17072021_19_38_16_AWEs_2BiGRU_1024d_pretrained_CAE_TF03_RUS_FBANK_144.pth'
    RUS: '17072021_17_14_29_AWEs_2BiGRU_1024d_pretrained_CAE_TF03_RUS_FBANK_143.pth'
    BUL: '16072021_15_18_46_AWEs_2BiGRU_1024d_pretrained_CAE_TF03_BUL_FBANK_150.pth'
    #HRV: '03062021_18_07_16_AWEs_2BiGRU_seq2seq_HRV_FBANK_94.pth'
    FRA: '16072021_14_47_46_AWEs_2BiGRU_1024d_pretrained_CAE_TF03_FRA_FBANK_150.pth'
    DEU: '16072021_14_44_00_AWEs_2BiGRU_1024d_pretrained_CAE_TF03_DEU_FBANK_150.pth'

#pretrained_model: '12032021_23_04_44_AWEs_2BiGRU_CZE_1024d_sia_02drop_FBANK_98.pth'
#pretrained_model: '12052021_16_11_10_AWEs_2BiGRU_CZE_1024d_sia_02drop_FBANK_88.pth'
#word_dist_dic: '/RSA_word_phonology/metadata/cze_eval_word2dist.pkl'
#save_fig: '/RSA_word_phonology/figures/cze_sia_hard_hist_'
#save_dict: '/acoustic_word_embeddings/cls_deu_vec'
#
input_signal_params:
    acoustic_features: 'FBANK'
    max_num_frames: 120
    sampling_rate: 16000

#
acoustic_encoder:
    encoder_arch: 'BiGRU'
    spectral_dim: 39
    max_num_frames: 120
    hidden_state_dim: 512
    output_dim: 1024
    n_layers: 2
    unit_dropout_prob: 0.2
    frame_dropout: False # either frame_dropout or feature_dropout can be True
    feature_dropout: False
    signal_dropout_prob: 0.0
#

acoustic_decoder:
    encoder_arch: 'BiGRU'
    spectral_dim: 39
    max_num_frames: 120
    hidden_state_dim: 1024
    n_layers: 1
    unit_dropout_prob: 0.2
    frame_dropout: False # either frame_dropout or feature_dropout can be True
    feature_dropout: False
    signal_dropout_prob: 0.0
#
batch_size: 256
cuda: True
catch_keyboard_interrupt: True
reload_from_files: False
expand_filepaths_to_save_dir: True
