# CONFIG FILE FOR AN EXPERIMENT
data_dir: '/data/GP_FBANK_ALL_39/'
speech_metadata: '/RSA_word_phonology/metadata/gp_words_metadata_train_valid_32k_x.tsv'
model_save_dir: '/RSA_word_phonology/inprogress_models/'
seed: 8421 #1234 #1358
language_set: 'RUS'
dev_split: 'DEV'
sample_size: 30000
experiment_name: 'AWEs_2BiGRU_1024d_pretrained_CAE_TF03'

pretrained_model: '13072021_19_09_37_AWEs_2BiGRU_1024d_auto_encoder_CZE_FBANK_83.pth'
#pretrained_model: '14072021_11_35_00_AWEs_2BiGRU_1024d_auto_encoder_POL_FBANK_99.pth'
#pretrained_model: '14072021_11_36_00_AWEs_2BiGRU_1024d_auto_encoder_DEU_FBANK_100.pth'
#pretrained_model: '14072021_11_37_30_AWEs_2BiGRU_1024d_auto_encoder_FRA_FBANK_62.pth'
#pretrained_model: '14072021_11_39_31_AWEs_2BiGRU_1024d_auto_encoder_RUS_FBANK_100.pth'
#pretrained_model: '14072021_11_40_46_AWEs_2BiGRU_1024d_auto_encoder_BUL_FBANK_97.pth'
#pretrained_model: '16072021_18_09_46_AWEs_2BiGRU_1024d_auto_encoder_TF02_POR_FBANK_59.pth'

input_signal_params:
    acoustic_features: 'FBANK'
    max_num_frames: 120
    sampling_rate: 16000
#
acoustic_encoder:
    encoder_arch: 'BiGRU'
    spectral_dim: 39
    max_num_frames: 120
    hidden_state_dim: 512
    output_dim: 1024
    n_layers: 2
    unit_dropout_prob: 0.2
    frame_dropout: False # either frame_dropout or feature_dropout can be True
    feature_dropout: False
    signal_dropout_prob: 0.0
#
acoustic_decoder:
    encoder_arch: 'BiGRU'
    spectral_dim: 39
    max_num_frames: 120
    hidden_state_dim: 1024
    n_layers: 1
    unit_dropout_prob: 0.2
    frame_dropout: False # either frame_dropout or feature_dropout can be True
    feature_dropout: False
    signal_dropout_prob: 0.0
#
training_hyperparams:
    learning_rate: 0.001
    batch_size: 256
    num_epochs: 150
    early_stopping_criteria: 10
cuda: True
catch_keyboard_interrupt: True
reload_from_files: False
expand_filepaths_to_save_dir: True
