# CONFIG FILE FOR AN EXPERIMENT

data_dir: '/data/GP_FBANK_ALL_39/'
speech_metadata: '/RSA_word_phonology/metadata/gp_words_metadata_train_valid_32k_x.tsv'
model_save_dir: '/RSA_word_phonology/inprogress_models/'
seed: 1248 #1358
stimuli_language: 'DEU' # CZE DEU
model_languages: 'POR CZE POL RUS BUL FRA DEU' #
eval_split: 'DEV' #DEV' #EVA

pretrained_models:
    POR: '16072021_17_55_31_AWEs_2BiGRU_1024d_siamese_POR_FBANK_85.pth'
    #CZE: '13072021_10_35_41_AWEs_2BiGRU_1024d_siamese_FBANK_87.pth'
    CZE: '18072021_13_34_01_AWEs_2BiGRU_1024d_siamese_CZE_FBANK_95.pth'
    POL: '15072021_16_29_39_AWEs_2BiGRU_1024d_siamese_POL_FBANK_59.pth'
    RUS: '15072021_16_37_10_AWEs_2BiGRU_1024d_siamese_RUS_FBANK_51.pth'
    BUL: '15072021_16_35_54_AWEs_2BiGRU_1024d_siamese_BUL_FBANK_98.pth'
    #HRV: '03062021_18_07_16_AWEs_2BiGRU_seq2seq_HRV_FBANK_94.pth'
    FRA: '15072021_16_33_39_AWEs_2BiGRU_1024d_siamese_FRA_FBANK_56.pth'
    DEU: '15072021_16_32_54_AWEs_2BiGRU_1024d_siamese_DEU_FBANK_92.pth'

#pretrained_model: '12032021_23_04_44_AWEs_2BiGRU_CZE_1024d_sia_02drop_FBANK_98.pth'
#pretrained_model: '12052021_16_11_10_AWEs_2BiGRU_CZE_1024d_sia_02drop_FBANK_88.pth'
#word_dist_dic: '/RSA_word_phonology/metadata/cze_eval_word2dist.pkl'
#save_fig: '/RSA_word_phonology/figures/cze_sia_hard_hist_'
#save_dict: '/acoustic_word_embeddings/cls_deu_vec'
#
input_signal_params:
    acoustic_features: 'FBANK'
    max_num_frames: 120
    sampling_rate: 16000

#
acoustic_encoder:
    encoder_arch: 'BiGRU'
    spectral_dim: 39
    max_num_frames: 120
    hidden_state_dim: 512
    output_dim: 1024
    n_layers: 2
    unit_dropout_prob: 0.2
    frame_dropout: False # either frame_dropout or feature_dropout can be True
    feature_dropout: False
    signal_dropout_prob: 0.0
#
batch_size: 256
cuda: True
catch_keyboard_interrupt: True
reload_from_files: False
expand_filepaths_to_save_dir: True
