# CONFIG FILE FOR AN EXPERIMENT
data_dir: '/data/GP_FBANK_ALL_39/'
speech_metadata: '/RSA_word_phonology/metadata/gp_words_metadata_train_valid_32k.tsv'
model_save_dir: '/RSA_word_phonology/inprogress_models/'
seed: 8421 #1234 #1358
language_set: 'DEU' 
dev_split: 'DEV'
sample_size: 30000
experiment_name: 'AWEs_2BiGRU_1024d_CAE'
#
input_signal_params:
    acoustic_features: 'FBANK'
    max_num_frames: 120
    sampling_rate: 16000
#
acoustic_encoder:
    encoder_arch: 'BiGRU'
    spectral_dim: 39
    max_num_frames: 120
    hidden_state_dim: 512
    output_dim: 1024
    n_layers: 2
    unit_dropout_prob: 0.2
    frame_dropout: False # either frame_dropout or feature_dropout can be True
    feature_dropout: False
    signal_dropout_prob: 0.0
#
acoustic_decoder:
    encoder_arch: 'BiGRU'
    spectral_dim: 39
    max_num_frames: 120
    hidden_state_dim: 1024
    n_layers: 1
    unit_dropout_prob: 0.2
    frame_dropout: False # either frame_dropout or feature_dropout can be True
    feature_dropout: False
    signal_dropout_prob: 0.0
#
training_hyperparams:
    learning_rate: 0.001
    batch_size: 256 
    num_epochs: 250
    early_stopping_criteria: 10
cuda: True
catch_keyboard_interrupt: True
reload_from_files: False
expand_filepaths_to_save_dir: True
